### PR TITLE
Basic cordova build

### PR DESCRIPTION
**Pull request by TehShrike**
That cordova directory adds a lot of noise, sorry about that.  Hit the package.json for the main things to know.

### CODE REVIEW

**Comment by njbotkin** [comment]
Haha, yeah, it does.  I thought the platforms/android and platforms/ios directories could be ignored?  Don't those files get generated by cordova?  Or are there important config files in there?

**Comment by TehShrike** [comment]
They're all project files created by `cordova create`, `cordova platform add ios`, and `cordova platform add android`... 

Oh hey, a relevant [StackOverflow answer!](https://stackoverflow.com/a/29972835/201789)

**Comment by TehShrike** [comment]
There we go, it's a lot better without `platforms` at least.

**Comment by TehShrike** [comment]
And even better without `cordova/plugins`.

**Comment by njbotkin** [comment]
Woohoo!

**Pull request merged**
